// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"memo/internal/apps"
	"memo/internal/bootstrap"
	"memo/internal/command"
	"memo/internal/configs"
	"memo/internal/memo"
	"memo/internal/user"
)

// Injectors from wire.go:

func initPollingBot() (*apps.PollingBot, error) {
	telegramConfig := configs.GetTelegramConfig()
	botAPI, err := bootstrap.NewTgBot(telegramConfig)
	if err != nil {
		return nil, err
	}
	parser := command.NewParser()
	appConfig := configs.GetAppConfig()
	dbConfig := configs.GetDBConfig()
	db, err := bootstrap.NewGORMDb(dbConfig)
	if err != nil {
		return nil, err
	}
	repository := memo.NewRepository(db)
	userRepository := user.NewRepository(db)
	randExecutor := bootstrap.NewRandExecutor(appConfig, repository, botAPI, userRepository)
	startExecutor := command.NewStartExecutor(userRepository, botAPI)
	addExecutor := command.NewAddExecutor(repository, botAPI, userRepository)
	defaultCommandExecutor := bootstrap.NewDefaultCommandExecutor(addExecutor)
	commandExecutors := bootstrap.NewCommandExecutors(randExecutor, startExecutor, defaultCommandExecutor)
	pollingBot := bootstrap.NewPollingBot(botAPI, telegramConfig, parser, commandExecutors)
	return pollingBot, nil
}
