// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"memo/configs"
	"memo/internal/apps"
	"memo/internal/bootstrap"
	"memo/internal/infra"
)

// Injectors from wire.go:

func initRandCommand() (*apps.RandCommand, error) {
	appConfig := configs.GetAppConfig()
	dbConfig := configs.GetDBConfig()
	db, err := bootstrap.NewGORMDb(dbConfig)
	if err != nil {
		return nil, err
	}
	memoGORMRepository, err := infra.NewMemoGORMRepository(db)
	if err != nil {
		return nil, err
	}
	userGORMRepository := infra.NewUserGORMRepository(db)
	telegramConfig := configs.GetTelegramConfig()
	botAPI, err := bootstrap.NewTgBot(telegramConfig)
	if err != nil {
		return nil, err
	}
	randCommand := bootstrap.NewRandCommand(appConfig, memoGORMRepository, userGORMRepository, botAPI)
	return randCommand, nil
}
